
package stock;

import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import org.apache.poi.ss.usermodel.DateUtil;



public class Magazin extends javax.swing.JFrame {
    connectDatabase con=new connectDatabase();
    ResultSet rs;
    DefaultTableModel tbl=new DefaultTableModel();
    int row;
    public Magazin() {
        initComponents();
        Imagetitle();
        tbl=(DefaultTableModel) jTable1.getModel();
        tblUpdate();
        combo1Update();
        combodata();
        qt_initial.setEditable(false);
        totaux();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        comboExiste = new javax.swing.JComboBox<>();
        numArticleCashe1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        inputDateEntree = new com.toedter.calendar.JDateChooser();
        inputqt = new com.toedter.components.JSpinField();
        inputPV = new javax.swing.JTextField();
        num_sortie = new javax.swing.JLabel();
        qt_initial = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        inputFiltre = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Information Magazin");
        setBackground(new java.awt.Color(255, 255, 255));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 102, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton1.setText("Ajouter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 80, 40));

        jLabel7.setText("Produit :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 50, 30));

        comboExiste.setOpaque(false);
        comboExiste.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboExisteItemStateChanged(evt);
            }
        });
        comboExiste.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                comboExistePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jPanel1.add(comboExiste, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 210, 30));

        numArticleCashe1.setBackground(new java.awt.Color(255, 255, 255));
        numArticleCashe1.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jPanel1.add(numArticleCashe1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 110, 10));

        jLabel8.setText("Quantite :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 60, 30));

        jLabel9.setText("P.V :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 50, 30));

        jLabel10.setText("Date d'Entree :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 80, 30));

        jButton2.setBackground(new java.awt.Color(204, 0, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton2.setText("Supprimer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, 90, 40));

        jButton3.setBackground(new java.awt.Color(0, 153, 153));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton3.setText("Modifier");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 100, 80, 40));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stock/petitexcel.png"))); // NOI18N
        jButton4.setText("Exporter vers Excel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 620, 200, 50));

        inputDateEntree.setDateFormatString(" yyyy-MM-dd"); // NOI18N
        jPanel1.add(inputDateEntree, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 140, 30));

        inputqt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputqtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inputqtMouseEntered(evt);
            }
        });
        jPanel1.add(inputqt, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 160, 30));

        inputPV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPVActionPerformed(evt);
            }
        });
        jPanel1.add(inputPV, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 210, 30));

        num_sortie.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        num_sortie.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(num_sortie, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 80, 10));

        qt_initial.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        qt_initial.setText("Quantite restant dans Stock 1:");
        qt_initial.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        qt_initial.setMargin(new java.awt.Insets(2, 5, 2, 2));
        qt_initial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qt_initialActionPerformed(evt);
            }
        });
        jPanel1.add(qt_initial, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 620, 300, 50));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder("<html>\n<h3>Enregistrement du Bon de requisition Magazin :<h3>"));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 790, 150));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº Article", "Nom de l'Article", "Quantité entrant", "Mesure par", "P.V (Fbu)", "Valeur Total (Fbu)", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(40);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(40);
            jTable1.getColumnModel().getColumn(1).setMinWidth(120);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(90);
            jTable1.getColumnModel().getColumn(2).setMinWidth(80);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(30);
            jTable1.getColumnModel().getColumn(3).setMinWidth(30);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(30);
            jTable1.getColumnModel().getColumn(4).setMinWidth(90);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(90);
            jTable1.getColumnModel().getColumn(5).setMinWidth(150);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(15);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 1000, 460));

        inputFiltre.setForeground(new java.awt.Color(153, 153, 153));
        inputFiltre.setText("Rechercher");
        inputFiltre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputFiltreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputFiltreFocusLost(evt);
            }
        });
        inputFiltre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputFiltreActionPerformed(evt);
            }
        });
        inputFiltre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputFiltreKeyReleased(evt);
            }
        });
        jPanel1.add(inputFiltre, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 60, 190, 40));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "Octobre", "November", "December" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox1PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 110, 90, 30));

        jComboBox2.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox2PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 110, 90, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 1030, 20));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Totaux :");
        jLabel1.setAlignmentY(2.0F);
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 620, 360, 50));

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton5.setText("Bon de requisition");
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 620, 120, 50));

        jMenu1.setText("Tâches");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Actualiser");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Retour aux infos du Stock ");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Retour au Management");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem6.setText("Exporter  vers Excel");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem8.setText("Déconnecter");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edition");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jCheckBoxMenuItem1.setText("Mode Sombre");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jCheckBoxMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Informations");
        jMenu3.setEnabled(false);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Stock ");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Magasin");
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Actualiser");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1015, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      if(numArticleCashe1.getText().isEmpty()|| inputqt.getValue()<=0 || inputPV.getText().isEmpty() || ((JTextField)inputDateEntree.getDateEditor().getUiComponent()).getText().isEmpty()){
          
          JOptionPane.showMessageDialog(null, "Veillez remplir tous les champs ! ");
      }
      else{
        String query="insert into tb_sorties(num_produit,qt_sortie,pv,stock,date_sortie) values ("+numArticleCashe1.getText()+","+inputqt.getValue()+","+inputPV.getText()+",'Stock 1','"+((JTextField)inputDateEntree.getDateEditor().getUiComponent()).getText()+"')";
        try {
            con.updateData(query);
            tblUpdate();
            num_sortie.setText("");
            inputqt.setValue(0);
            inputPV.setText("");
            qt_initial.setText("");
            
        } catch (Exception e) {
        }
      } 
       
      
        
    }//GEN-LAST:event_jButton1ActionPerformed
      
    
    
    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
     
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Magazin n=new Magazin();
        n.setLocationRelativeTo(this);
        pack();
        n.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        String query="delete from tb_sorties where num_produit="+num_sortie.getText()+"";
        try {
            if(JOptionPane.showConfirmDialog(rootPane,"Voulez-vous supprimer cet article  ?",null,JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION){
                con.updateData(query);
                tblUpdate();
                num_sortie.setText("");
                inputqt.setValue(0);
                inputPV.setText("");
                qt_initial.setText("");
            }
            
        } catch (Exception e) {
        }
            
            
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      if(numArticleCashe1.getText().isEmpty()|| inputqt.getValue()<=0 || inputPV.getText().isEmpty() || ((JTextField)inputDateEntree.getDateEditor().getUiComponent()).getText().isEmpty()){
          
          JOptionPane.showMessageDialog(null, "Veillez remplir tous les champs ! ");
      }
      else{
          
           String query="update tb_sorties set num_produit="+numArticleCashe1.getText()+",qt_sortie="+inputqt.getValue()+",pv="+inputPV.getText()+",stock='Stock 1',date_sortie='"+((JTextField)inputDateEntree.getDateEditor().getUiComponent()).getText()+"' where num_sortie="+num_sortie.getText()+" ";
        try {
              if(JOptionPane.showConfirmDialog(rootPane,"Voulez-vous modifier cet article  ?",null,JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION){
                  con.updateData(query);
                  tblUpdate();
                  numArticleCashe1.setText("");
                  inputPV.setText("");
                  inputqt.setValue(0);
                  qt_initial.setText("");
              }
              
            
        } catch (Exception e) {
        }
          
      }
      
        
        
       
      
              

        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void comboExistePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_comboExistePopupMenuWillBecomeInvisible
        String a=comboExiste.getSelectedItem().toString();
        numeroCashe(a,numArticleCashe1);
         String b="select concat('Quantite restant dans Stock 1 : ',(sum(quantite)+quantite_initial)-sum(distinct qt_sortie)) as 'SF' from tb_entrees,tb_sorties where tb_entrees.num_produit="+numArticleCashe1.getText()+" and tb_entrees.num_produit=tb_sorties.num_produit and tb_entrees.stock='Stock 1'";
        
        try {
            rs=con.extaireData(b);
            while(rs.next())
            qt_initial.setText(rs.getString("SF"));
        } catch (SQLException ex) {
            
        }
        
        if(qt_initial.getText().isEmpty())
        {
          String c="select concat('Quantite restant dans Stock 1 : ',quantite+quantite_initial) as 'SF' from tb_entrees where tb_entrees.num_produit="+numArticleCashe1.getText()+" and stock='Stock 1' order by date_entree desc limit 1";
        
        try {
            rs=con.extaireData(c);
            while(rs.next())
            qt_initial.setText(rs.getString("SF"));
        } catch (SQLException ex) {
            
        }  
        }
         
    }//GEN-LAST:event_comboExistePopupMenuWillBecomeInvisible

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Export_Excel e=new Export_Excel(jTable1, this);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void inputFiltreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputFiltreKeyReleased
        String e=inputFiltre.getText();
        filtrer(e);
        totaux();
    }//GEN-LAST:event_inputFiltreKeyReleased

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        Magazin n=new Magazin();
        n.setLocationRelativeTo(this);  
        pack();
        n.setVisible(true);   
        dispose();
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Stock1 n=new Stock1();
        n.setLocationRelativeTo(this);
        pack();
        n.setVisible(true);        
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
       
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int selected=jTable1.getSelectedRow();
        int numero=Integer.parseInt(jTable1.getModel().getValueAt(selected,0).toString());
        String cashe=jTable1.getModel().getValueAt(selected,0).toString();
        String nom=jTable1.getModel().getValueAt(selected,1).toString();
        int qt=Integer.parseInt(jTable1.getModel().getValueAt(selected,2).toString());
        String pu=jTable1.getModel().getValueAt(selected,4).toString();
        Date date=DateUtil.parseYYYYMMDDDate(jTable1.getModel().getValueAt(selected,6).toString());
       
        
            
            
                numArticleCashe1.setText(cashe);
                comboExiste.setSelectedItem(nom);
                inputqt.setValue(qt);
                inputPV.setText(pu);
                inputDateEntree.setDate(date);
                
                 try {
                    
                    String query="select num_sortie from tb_sorties where num_produit="+numero+" and qt_sortie="+qt+" and pv="+pu+"  and date_sortie='"+((JTextField)inputDateEntree.getDateEditor().getUiComponent()).getText()+"' ";
                    rs=con.extaireData(query);
                    while(rs.next()){
                        num_sortie.setText(rs.getString("num_sortie"));
                    }
                
                } catch (Exception e) {
                }
                 
            String b="select concat('Quantite restant dans Stock 1: ',(sum(quantite)+quantite_initial)-sum(distinct qt_sortie)) as 'SF' from tb_entrees,tb_sorties where tb_entrees.num_produit="+numArticleCashe1.getText()+" and tb_entrees.num_produit=tb_sorties.num_produit";
        
        try {
            rs=con.extaireData(b);
            while(rs.next())
            qt_initial.setText(rs.getString("SF"));
        } catch (SQLException ex) {
            
        }
            
                
           

        
        
       
    }//GEN-LAST:event_jTable1MouseClicked

    private void inputFiltreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputFiltreFocusGained
        if(inputFiltre.getText().equals("Rechercher"))
        {
            inputFiltre.setText("");
            inputFiltre.setForeground(Color.black);
            
        }
    }//GEN-LAST:event_inputFiltreFocusGained

    private void inputFiltreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputFiltreFocusLost
        if(inputFiltre.getText().equals(""))
        {
            inputFiltre.setText("Rechercher");
            inputFiltre.setForeground(new Color(153, 153, 153));
           
        }
    }//GEN-LAST:event_inputFiltreFocusLost

    private void inputFiltreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputFiltreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputFiltreActionPerformed

    private void comboExisteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboExisteItemStateChanged
        
    }//GEN-LAST:event_comboExisteItemStateChanged

    private void inputqtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputqtMouseClicked
        
    }//GEN-LAST:event_inputqtMouseClicked

    private void inputqtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputqtMouseEntered
        
    }//GEN-LAST:event_inputqtMouseEntered

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Stock1 t=new Stock1();
        t.setVisible(true);
        t.setLocationRelativeTo(this);
        pack();
        dispose();
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void inputPVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPVActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        Management t=new Management();
        t.setVisible(true);
        pack();
        t.setLocationRelativeTo(this);
        dispose();        
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        Export_Excel e=new Export_Excel(jTable1, this);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jComboBox1PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox1PopupMenuWillBecomeInvisible
       String query="select numero_prod,nom_prod,qt_sortie,unite_de_mesure,pv,qt_sortie*pv as 'pv_total',date_sortie from tb_produit,tb_entrees,tb_sorties where date_format(date_sortie,'%M')='"+jComboBox1.getSelectedItem()+"' and year(date_sortie)="+jComboBox2.getSelectedItem()+" and numero_prod=tb_entrees.num_produit and tb_entrees.num_produit=tb_sorties.num_produit group by num_sortie desc";
       try {
        
          rs=con.extaireData(query);
          tbl.setRowCount(0);
          while(rs.next())
          {
             tbl.addRow(new Object[]{
             rs.getString("numero_prod"),
             rs.getString("nom_prod"),
             rs.getString("qt_sortie"),
             rs.getString("unite_de_mesure"),
             rs.getString("pv"), 
             rs.getString("pv_total"),
             rs.getString("date_sortie")
          
             });
           }
          
           } catch (Exception e) {
        
             } 
                totaux();
    }//GEN-LAST:event_jComboBox1PopupMenuWillBecomeInvisible

    private void jComboBox2PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox2PopupMenuWillBecomeInvisible
        String query="select numero_prod,nom_prod,qt_sortie,unite_de_mesure,pv,qt_sortie*pv as 'pv_total',date_sortie from tb_produit,tb_entrees,tb_sorties where date_format(date_sortie,'%M')='"+jComboBox1.getSelectedItem()+"' and year(date_sortie)="+jComboBox2.getSelectedItem()+" and numero_prod=tb_entrees.num_produit and tb_entrees.num_produit=tb_sorties.num_produit group by num_sortie desc";
       try {
        
          rs=con.extaireData(query);
          tbl.setRowCount(0);
          while(rs.next())
          {
             tbl.addRow(new Object[]{
             rs.getString("numero_prod"),
             rs.getString("nom_prod"),
             rs.getString("qt_sortie"),
             rs.getString("unite_de_mesure"),
             rs.getString("pv"), 
             rs.getString("pv_total"),
             rs.getString("date_sortie")
          
             });
           }
          
           } catch (Exception e) {
        
             } 
       totaux();
    
    }//GEN-LAST:event_jComboBox2PopupMenuWillBecomeInvisible

    private void qt_initialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qt_initialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qt_initialActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        login l=new login();
        l.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem8ActionPerformed
    public void Imagetitle()
     {
      setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon-dashboard-9.png")));
     }
    public void tblUpdate()
    {
    //String query="select numero_prod,nom_prod,quantite-qt_sortie as 'stock_initial',quantite,qt_sortie,quantite-qt_sortie as 'S.F'  from tb_entrees,tb_produit,tb_sorties where numero_prod=tb_entrees.num_produit and tb_entrees.num_produit=tb_sorties.num_produit group by numero_prod ";
      String query="select numero_prod,nom_prod,qt_sortie,unite_de_mesure,pv,qt_sortie*pv as 'pv_total',date_sortie from tb_produit,tb_entrees,tb_sorties where numero_prod=tb_entrees.num_produit and tb_entrees.num_produit=tb_sorties.num_produit and tb_sorties.stock='Stock 1' group by num_sortie desc; ";
       try {
        
          rs=con.extaireData(query);
          tbl.setRowCount(0);
          while(rs.next())
          {
             tbl.addRow(new Object[]{
             rs.getString("numero_prod"),
             rs.getString("nom_prod"),
             rs.getString("qt_sortie"),
             rs.getString("unite_de_mesure"),
             rs.getString("pv"), 
             rs.getString("pv_total"),
             rs.getString("date_sortie")
          
             });
           }
          
           } catch (Exception e) {
        
             } 
    
         }
        

 public void combo1Update()
    {
        String query="select * from  tb_produit";
        
        try {
              rs=con.extaireData(query);
              while(rs.next())
              {
                  comboExiste.addItem(rs.getString("nom_prod"));
                  
              }
        } catch (Exception e) {
        }
    }
public void numeroCashe(String nom,JLabel l)
{
    String query="select numero_prod from tb_produit where nom_prod='"+nom+"'";
    try {
          rs=con.extaireData(query);
          while(rs.next())
          {
              l.setText(rs.getString("numero_prod"));
              
          }
    } catch (Exception e) {
    }
}
public void filtrer(String filtra){
    TableRowSorter<DefaultTableModel> tbRs=new TableRowSorter<DefaultTableModel>(tbl);
    jTable1.setRowSorter(tbRs);
    tbRs.setRowFilter(RowFilter.regexFilter(filtra));

}

public void alternateColor(){
    
       
}
 public void combodata(){
        
        String query="select distinct DATE_FORMAT(date_sortie,'%Y') as 'date' from tb_sorties";
        
        try {
              
              rs=con.extaireData(query);
              jComboBox2.removeAllItems();
              while(rs.next()){
                  jComboBox2.addItem(rs.getString("date"));
              }
            
        } catch (Exception e) {
        }
    }
   public void totaux(){
     
     long sum = 0;
     for(int i=0;i<jTable1.getRowCount();i++){
          
         String stock=jTable1.getValueAt(i,4).toString();
         sum+=Long.parseLong(stock);
           
       }
       jLabel1.setText("Totaux :"+sum+" Fbu");
       
   }
    public static void main(String args[]) {
        
        try {
            UIManager.setLookAndFeel(new FlatMacLightLaf());
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        new Magazin().setVisible(true);
         
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboExiste;
    private com.toedter.calendar.JDateChooser inputDateEntree;
    private javax.swing.JTextField inputFiltre;
    private javax.swing.JTextField inputPV;
    private com.toedter.components.JSpinField inputqt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel numArticleCashe1;
    private javax.swing.JLabel num_sortie;
    private javax.swing.JTextField qt_initial;
    // End of variables declaration//GEN-END:variables
}
